on:
  push:
    branches:
    - main
  schedule:
  - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: schmiddim/action-wget-unzip@v2
      with:
        url: https://saraksti.rigassatiksme.lv/riga/gtfs.zip
        destination: RS/
    - run: wget https://download.geofabrik.de/europe/latvia-latest.osm.pbf
    - run: wget -O noteikumi.txt https://likumi.lv/ta/id/198589
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: dotnet restore
    - run: dotnet build --configuration Release --no-restore
    - run: dotnet run --project Osmalyzer
