on:
  push:
    branches:
    - main
  schedule:
  - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache external data
      uses: actions/cache@v3
      env:
        cache-name: osmalyzer-external-data
      with:
        path: cache/
        # just a random string as key
        key: txLyWHOIazMqZvNZixBh
    
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: dotnet restore
    - run: dotnet build --configuration Release --no-restore -p:ExtraDefineConstants=REMOTE_EXECUTION
    - run: dotnet run --project Osmalyzer
    #- run: |-
    #    mkdir _site &&
    #    cp "Rigas Satiksme report.txt" _site
    #- uses: actions/upload-pages-artifact@main
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
