on:
  workflow_run:
    workflows:
    - main
    types:
    - completed

jobs:
  zulip:
    if: ${{ github.event.workflow_run.conclusion != 'success' && github.event.workflow_run.conclusion != 'cancelled' }}
    runs-on: ubuntu-latest
    steps:
    - uses: zulip/github-actions-zulip/send-message@v1.0.1
      with:
        email: ${{ secrets.ZULIP_BOT_EMAIL }}
        api-key: ${{ secrets.ZULIP_BOT_KEY }}
        organization-url: ${{ secrets.ZULIP_ORGANIZATION_URL }}
        to: ${{ secrets.ZULIP_STREAM }}
        type: stream
        topic: ${{ secrets.ZULIP_TOPIC }}
        content: >-
          Something went wrong with [workflow run](${{ github.event.workflow_run.html_url }}),
          conclusion: `${{ github.event.workflow_run.conclusion }}`.
